name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install --upgrade pip wheel
      - run: pip install bandit black codespell flake8 flake8-2020 flake8-bugbear
                         flake8-comprehensions isort mypy pytest pyupgrade safety
      - run: bandit --recursive --skip B110 .   # B110 is bare except
      - run: black --check . || true
      - run: codespell  # --ignore-words-list="" --skip="*.css,*.js,*.lock"
      - run: flake8 . --count --select=E9,F63,F7 --show-source --statistics
      - run: flake8 . --count --select=F82 --show-source --statistics || true  # Undefined names in issue #25
      - run: flake8 --ignore=B001,E221,E265,E302,E305,E402,E711,E712,E722,F401,F541,F811,F821,F841,R505,W292
                    --max-complexity=15 --max-line-length=114 --show-source --statistics .
      - run: isort --check-only --profile black . || true
      - run: pip install -r requirements.txt || pip install --editable . || pip install . || true
      - run: mkdir --parents --verbose .mypy_cache
      - run: mypy --ignore-missing-imports --install-types --non-interactive . || true
      - run: pytest . || true
      - run: pytest --doctest-modules . || true
      - run: shopt -s globstar && pyupgrade --py37-plus **/*.py || true
      - run: safety check
